### ISSUE TITLE
display

### ISSUE THREAD

**Issue by pcause** [hieuthi/joplin-plugin-metis#2]
I have this as a line in the todo section markdown:

2021-12-12  test [a note](https://www.wsj.com) [a file](file://wsl.localhost/f35c/home/phil/todo.txt) +proj #context due:2022-01-02

in the view display I get this:

![image](https://user-images.githubusercontent.com/1071479/145824039-42ac3d53-d77e-48ec-a7e8-d0b0b750594e.png)

I'd expect given todo.txt standard that the creation date (2021-12-12) would be first.  and I wouldn't have exoected the fields to be reordered other than showing the dropdown for the priority 

here is the link to the  [todo.txt format spec](https://github.com/todotxt/todo.txt)

added:  saw your parser and you know the spec.  suggestion: keep the order of itms per the user entered order.  users may have a style for where they enter meta tags (due:yyy-mm-dd).  you can add an "order" to the parser token

**Comment by hieuthi** [comment]
Completion and Creation Dates are rendered at the end deliberately for aesthetic purposes as they not always exists in a todo. This project is not a todo.txt plugin but a task manager plugin based on todo.txt so It will not always follow todo.txt specification.

I will consider add some options for customization or something, but given there is a lot of important features I want to implement first, that feature will not be implemented anytime soon.

**Comment by hieuthi** [comment]
Btw, this plugin was designed specifically for markdown split view, you will have a very bad time if you are using it with rich text editor as none of the features will work. And I have no plan to support rich text editor.
