### ISSUE TITLE
„Special chars“

### ISSUE THREAD

**Issue by BsNoSi** [hieuthi/joplin-plugin-metis#3]
This is a "very low level" issue:

![image](https://user-images.githubusercontent.com/2784683/152687028-044baef5-cac9-4d74-bde7-b36c62634a3b.png)

As you can see, a German umlaut stops marking project and content highlighter. Not hard to overcome (simply change ä → ae…) but *a little inconvenient* while fast typing. 

A typical "first world problem" – I know :)

**Comment by hieuthi** [comment]
This should be fixed in v0.1.5 1bd8e39c35b9dc0a4d467d27f7f9f1e308e6552e
