### ISSUE TITLE
Is this a limit?

### ISSUE THREAD

**Issue by BsNoSi** [hieuthi/joplin-plugin-metis#4]
Are priorities limited to five (A-E)?

![image](https://user-images.githubusercontent.com/2784683/152688354-236a04bb-b586-4b19-9984-67aa27fefbbb.png)

Not sure if this is an error or a wanted behavior. Pushing it to the end is correct, but changing the priority letter from "F" to "A"  ?

If there is a limit, out range priorities should be set to "none" in my opinion.

**Comment by hieuthi** [comment]
It is a visual bug, the sorting and filtering should still work correctly for A to Z. I will check if I have a fix for it when I got some time.

**Comment by hieuthi** [comment]
This should be fixed in v0.1.5 67311fcdc8fbd2e1cb39a88bac59ced4cbf08b5d
